---
abstract: 'Send SMS messages using txtlocal.co.uk'
author:
  - 'Edmund von der Burg  C<< <evdb@cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-SMS-TxtLocal
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  JSON: 2.16
  LWP::UserAgent: 0
  Moose: 0
  namespace::autoclean: 0
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
